<?xml version="1.0" encoding="utf-8"?><Database Name="MvcDemo" Class="SmsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=MvcDemo;Integrated Security=True" SettingsObjectName="MvcDemo.Dao.Properties.Settings" SettingsPropertyName="HLH_SMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RoleInfo" Member="RoleInfo">
    <Type Name="RoleInfo">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="AllowActList" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RemarkText" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="RoleInfo_UserRole" Member="UserRole" Storage="_SMS_UserRole" ThisKey="RoleId" OtherKey="RoleId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.UserSignInRecord" Member="UserSignInRecord">
    <Type Name="UserSignInRecord">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="SignInIp" Type="System.String" DbType="NVarChar(48)" CanBeNull="true" />
      <Column Name="SignInType" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="StatusCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="StatusMsg" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserInfo" Member="UserInfo">
    <Type Name="UserInfo">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="AllowActList" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DenyActList" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtensionNum" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="UserTitle" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="RemarkText" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UserInfo_UserRole" Member="UserRole" Storage="_SMS_UserRole" ThisKey="UserId" OtherKey="UserId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRole">
    <Type Name="UserRole">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="RoleInfo_UserRole" Member="RoleInfo" Storage="_SMS_RoleInfo" ThisKey="RoleId" OtherKey="RoleId" Type="RoleInfo" IsForeignKey="true" />
      <Association Name="UserInfo_UserRole" Member="UserInfo" Storage="_SMS_UserInfo" ThisKey="UserId" OtherKey="UserId" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserPreference" Member="UserPreference">
    <Type Name="UserPreference">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>